name: test_coverage

on: [push]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      GDF_ACCOUNT_JSON: ${{ secrets.GDF_ACCOUNT_JSON }}
      RASA_URL: ${{ secrets.RASA_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              python -m pip install --upgrade pip
              pip install -e .[all]
              pip install -r requirements_test.txt
          else
              make venv
          fi
        shell: bash

      - name: build coverage file
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pytest --cache-clear --cov=df_transitions tests/ > pytest-coverage.txt
          else
            make test
          fi
        shell: bash
